# Generated by Django 4.1.7 on 2023-03-22 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eps',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('date', models.TextField(blank=True, null=True)),
                ('epscalculated', models.FloatField(blank=True, db_column='epsCalculated', null=True)),
            ],
            options={
                'db_table': 'eps',
            },
        ),
        migrations.CreateModel(
            name='Marketcap',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('mccalculated', models.FloatField(blank=True, db_column='mcCalculated', null=True)),
            ],
            options={
                'db_table': 'marketcap',
            },
        ),
        migrations.CreateModel(
            name='QuarterlyData',
            fields=[
                ('stockid', models.IntegerField(db_column='stockID')),
                ('datemonthyear', models.TextField(db_column='dateMonthYear')),
                ('netincome', models.TextField(blank=True, db_column='netIncome', null=True)),
                ('sharesoutsanding', models.IntegerField(blank=True, db_column='sharesOutsanding', null=True)),
                ('quarterly_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'quarterly_data',
            },
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('stockinfoid', models.IntegerField(db_column='stockInfoID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('type', models.CharField(max_length=45)),
                ('current_value', models.IntegerField()),
            ],
            options={
                'db_table': 'stocks',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(db_column='userID', primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('email_id', models.CharField(max_length=45, unique=True)),
                ('age', models.IntegerField()),
                ('total_investment', models.IntegerField()),
                ('total_current_value', models.IntegerField()),
                ('total_pl', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ValuationStocks',
            fields=[
                ('stockid', models.IntegerField(db_column='stockId')),
                ('date', models.TextField(blank=True, null=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('adj_close', models.FloatField(blank=True, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('valuation_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'valuation_stocks',
            },
        ),
        migrations.CreateModel(
            name='YearlyData',
            fields=[
                ('stockid', models.IntegerField(db_column='StockID')),
                ('year', models.IntegerField(blank=True, db_column='Year', null=True)),
                ('average_stock_value', models.FloatField(blank=True, null=True)),
                ('outstanding_share', models.IntegerField(blank=True, null=True)),
                ('yearly_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'yearly_data',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionid', models.IntegerField(db_column='transactionID', primary_key=True, serialize=False)),
                ('investment', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('stockid', models.ForeignKey(db_column='stockID', on_delete=django.db.models.deletion.DO_NOTHING, to='users.stocks')),
                ('userid', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.DO_NOTHING, to='users.users')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
        migrations.CreateModel(
            name='CurrentHoldings',
            fields=[
                ('holdingid', models.IntegerField(db_column='holdingID', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('investment_in_stock', models.IntegerField()),
                ('stockholdid', models.ForeignKey(db_column='StockHoldID', on_delete=django.db.models.deletion.DO_NOTHING, to='users.stocks')),
                ('userid', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.DO_NOTHING, to='users.users')),
            ],
            options={
                'db_table': 'current_holdings',
            },
        ),
        migrations.CreateModel(
            name='PL',
            fields=[
                ('userid', models.OneToOneField(db_column='userid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='users.users')),
                ('p_l', models.FloatField()),
                ('stockid', models.ForeignKey(db_column='stockid', on_delete=django.db.models.deletion.DO_NOTHING, to='users.stocks')),
            ],
            options={
                'db_table': 'p_l',
                'unique_together': {('userid', 'stockid')},
            },
        ),
    ]
